Fix Grafana datasource configuration conflict
- Remove duplicate datasource configuration
- Use default datasources provided by kube-prometheus-stack chart
- Fixes CrashLoopBackOff error in Grafana pod

Error: "Only one datasource per organization can be marked as default"

Signed-off-by: Jaime Henao <jaime.andres.henao.arbelaez@ba.com>